language: ruby
rvm: 2.1.6p336
script:  bundle exec jekyll build
deploy:
    provider: s3
    bucket: www.quantgov.org
    skip_cleanup: true
    local_dir: _site
    on:
        branch: master
    access_key_id:
        secure: NbQjJGD+/hcNPLdgKBiJFndrbY7F3fAJ628BBUwfiJFZDN8nFlui5tDQWJtcZZeu9QtQp9aaZ4zNX59x022rgpavJVnQ4NTJyJoYSz4MpK+ipxdnhrWnpJ7pMhU4kKe9BGQp63cwyOKzfu0G2q6jr4fd+USzOeWMJUSwcct0pasZzugg+7Q9iVjraFqvWTquaWluTn/MrHwhLyrzVbZS/tbEen40sknDSnWSTNyRc4T/OMBxnznSxFl7Fo0wus64Vk/89P601RHQVSTqbkg5LPByv47xEJrFcI3Zvifj/E7cuYaS2zbFOsNwHlATsAwVX5YfmFZUhXNx1xfEfeHmrR2ZNsA/Due1Ays760oeBT67i6Qc0N1AOtBAeu63gaHeIjzHmMBtNIMnl3VHw0Gl4hxvret+dEJliohysJmVSGwXBc3yxTODckb0xGxpIOHEYWQvfIQKE8e8FC+JD5ovvC55jj7RB6CIwnmFbNz6g61BDI4UYHVICxaZ+A5UZVHWj8bBH3uPWXx3x5bBRjBmqz4fBPw4IF929Q9zqAKdi+h8G/1OEVxHv4xQU9T1/1a88cy/ryxffiSrOZ+qoxt6l8RZTE6wFLhnmvLg3qsheiJWfoEfC2dTN8usgdbERH+uYW2Zm9nEsDwZyLOtINX5A/Wttn4KFBfy/Vj/sUEF22Y=
    secret_access_key:
        secure: rbk6Grw18hSGVSFojLme7u0e6XWm5Yv3/FcSZNRAguO1WZh8EQ23Md4JlsYLf+C3gMnYMkwglvfA+BRBtnUHAn6GSjPBj6DMnWTBQQfhyPYjglDCHQdhzCVCJwFMRvAtOjOuM89CmNcm19e38vzJWGzLK8TNk9z3YK0PQXk28qNs/NmmnZ86uyDW7wzOh8RSb3KXPSneOaDOsFLhJS1Hz5KyUKvifuuAUpInymehBeb7Uz4BLGY30+QMEUZjL5L5Ut5OcUzxWtBWQuG2HZy443YD7Ea/fkB/rUGh4DAFiOuSySfovd924k8zQd1biPKpZTPgeQvxyO7ptolZodDO0fhwnx4udH1fxJOBIBj79F7Z5Hme0OMl66zXbYNreJChxF4X5KZCFGL6qkl/x2o17V1I588Ooneonp/Esr1rF/P3FZVWSktE/CvmtAd98/bmKIoK6qmen6yRHIFdIak3UQe1OBhBJpFsoeN+RY30/f6wzjpVEZxet8u/5jvivUDt1dNjJWRYw/gVHFRWQeeRuJtk8HwbFs11aMsDsZ2pblFkL6h1hAdmWBdXtwnbd51AnQ2rF0BSdtysvoMBRz+gG9c7jsV5RqW4a/fmSp3cRrJNuCwh5JXCuk3DBE2ExEjl3qQlLgmA7WuhXQWbfSvAE12v0P4fgAK0wWIuIwQkzko=
